name: Windows - RustDesk Runtime Accumulator

on:
  workflow_dispatch:

jobs:
  accumulate_runtime:
    name: Accumulate Runtime
    runs-on: windows-latest
    timeout-minutes: 360 # Maximum allowed job duration

    steps:
      - name: Downloading & Installing Essentials
        run: |
          # Insert the commands for downloading and installing here
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: |
          # Insert the commands for logging into AnyDesk here
          cmd /c show.bat

      - name: Time Counter
        run: |
          # Insert the Python script (time.py) here
          python time.py
